script:
- docker build --target test --tag todo-app:test .
- docker run todo-app:test todo_app/tests/test_trello.py
- docker run --env-file .env.test todo-app:test todo_app/tests/test_app.py
- docker run --env TRELLO_BOARD_ID --env TRELLO_AUTH --env TRELLO_TOKEN todo-app:test todo_app/tests_e2e/test_e2e.py