version: "3"

services:
  todo-app:
    image: todo-app:dev
    build: 
        context: .
        dockerfile: Dockerfile
        target: development
    ports:
      - "8089:5000"
    env_file:
        - .env
    volumes:
      - type: bind
        source: ./todo_app
        target: /app/todo_app
  
  todo-app-test:
    image: todo-app:test
    build: 
        context: .
        dockerfile: Dockerfile
        target: test
    env_file:
        - .env
    volumes:
        - type: bind
          source: ./todo_app
          target: /app/todo_app
  
    